### ISSUE TITLE
Why dependency on `eightpoints/guzzle-wsse-middleware`

### ISSUE THREAD

**Issue by ruudk** [8p/GuzzleBundle#126]
Why does this bundle has a dependency on eightpoints/guzzle-wsse-middleware?

**Comment by florianpreusner** [comment]
Well that dependency is very old and the reason why this bundle exists. Cause a couple of years ago I was looking for a nice solution to integrate WSSE. But you are right. This dependency should be optional. That's why following issue was created: https://github.com/8p/GuzzleBundle/issues/73

If you have a great idea how to integrate plugins nicely in a bundle let me know. I appreciate any recommendations. 👍 

Going to close this issue because of already existing one.
